broadinstitute/monster-deploy

.gitignore, README.md, environments/dev/terraform/aws.tf, environments/dev/terraform/backend.tf, environments/dev/terraform/dns.tf, environments/dev/terraform/providers.tf, environments/dev/terraform/version.tf
There's a lot more we could do here, but I'm keeping it simple for now.
=> DSPDC-422 Initialize dev environment with DNS and S3.

environments/dev/k8s/experiments-k8s-cluster/kubectl, environments/dev/k8s/init-configs/00-pod-running-policy.yaml, environments/dev/k8s/init-configs/01-pod-runner-role.yaml, environments/dev/terraform/k8s.tf, environments/dev/terraform/networks.tf, environments/dev/terraform/providers.tf, environments/dev/terraform/services.tf
Mainly a copy-paste of configs from the other repo
=> Add configs for a test k8s cluster.

environments/dev/terraform/aws.tf, environments/dev/terraform/k8s.tf, environments/dev/terraform/version.tf
=> Fix AWS policy for test user.

environments/dev/terraform/aws.tf, environments/dev/terraform/command-center.tf, environments/dev/terraform/variables.tf, templates/terraform/command-center-project/cloudsql.tf, templates/terraform/command-center-project/provider.tf, templates/terraform/command-center-project/variables.tf
Pretty much copied from dsp-ingest-deploy.
=> DSPDC-669 Add CloudSQL instance and account to command center.

hack/init-environment.sh
[Jira Ticket](https://broadinstitute.atlassian.net/browse/DSPDC-682)
Just adding a namespace for CloudSQLProxy
=> Add cloudsql-proxy namespace to monster-deploy

README.md, environments/README.md, hack/README.md, hack/apply-terraform, hack/init-environment.sh
Starting with the Terraform piece since other tickets in the sprint depend on it.
=> DSPDC-729 Split out terraform script.

environments/dev/terraform/clinvar.tf, templates/terraform/k8s-master/main.tf
Noticed some things while working on my SPIKE ticket / splitting up scripts that don't really fit into a bucket of work. Opening here so it's easy to see, will comment explanations inline.
=> Random TF cleanups.

hack/README.md, hack/apply-cluster-resources, hack/apply-helm-releases, hack/apply-terraform, hack/common.sh, templates/terraform/cloudsql/main.tf, templates/terraform/command-center-project/cloudsql.tf
* Renamed `init-environment.sh` to be specifically about Helm
* Also renamed `init-cluster-resources` to be `apply-cluster-resources`, since `init` implies creation but the script is really doing a create-or-update
* Finally, created a tiny `common.sh` file to hold constants and functions used across executable scripts
=> DSPDC-729 Finish rearranging script contents

.gitignore, environments/README.md, environments/dev/terraform/variables.tf, hack/apply-helm-releases, hack/apply-terraform, hack/common.sh, templates/helm/command-center/Chart.yaml, templates/helm/command-center/templates/cloudsql-proxy.yaml, templates/helm/command-center/values.schema.json, templates/helm/crd-operators/Chart.yaml, templates/helm/crd-operators/templates/secret-manager.yaml, templates/helm/crd-operators/values.schema.json, templates/helm/crd-operators/values.yaml
I think I like it now that it's working, but I'm curious to hear what others think!
=> DSPDC-679 Consolidate Helm releases into a single chart, using Flux

templates/terraform/processing-project/service-accounts.tf
[Jira Ticket](https://broadinstitute.atlassian.net/browse/DSPDC-701)
Creating a new service account (for processing projects) to run Argo pods.
=> Create processing project service account to run argo pods

environments/v2f-prod/README.md, environments/v2f-prod/terraform/backend.tf, environments/v2f-prod/terraform/bucket.tf
Added benefit of splitting up our bash: We can create one-off Terraforms without hacking around our "core" Helm releases!
=> DSPDC-769 Set up new V2F env with bucket.

environments/v2f-prod/terraform/bucket.tf
Double-checked the result of `apply`-ing in the cloud console this time.
=> DSPDC-769 Fix project for V2F bucket.

hack/apply-cluster-resources, hack/apply-helm-releases, hack/common.sh, templates/helm/command-center/templates/argo-controllers.yaml, templates/helm/command-center/templates/argo.yaml, templates/helm/command-center/values.schema.json, templates/terraform/cloudsql/main.tf
Draft because this will need to change based on review of broadinstitute/monster-helm#3, but putting it out there so people can see how the chart is used.
=> DSPDC-650 Add Argo controller installation to every processing ns.

environments/v2f-prod/terraform/bucket.tf, templates/helm/command-center/templates/argo.yaml, templates/terraform/google-sa/outputs.tf
Quick fixes to make stuff actually werk
=> fix the things

environments/v2f-prod/terraform/bucket.tf
Quick fix to reflect applied terraform changes
=> fix v2f writer things

environments/v2f-prod/terraform/bucket.tf
Adding a group by email to the v2f bucket ([Jira Ticket](https://broadinstitute.atlassian.net/browse/DSPDC-825)).
=> Add group to existing v2f bucket

hack/apply-cluster-resources, hack/apply-helm-releases, hack/common.sh, templates/helm/command-center/templates/argo.yaml
The script logic is all about installing to processing-project GKEs, which we don't need any more.
=> Bump Argo, and remove outdated script logic.

hack/apply-cluster-resources, hack/common.sh, templates/helm/command-center/templates/argo.yaml, templates/helm/command-center/templates/clinvar.yaml
=> DSPDC-832 Add cron values, and upgrade other stuffs.

templates/terraform/processing-project/buckets.tf
Found while loading one of the new ClinVar test runs into the dev repo.
=> Fix IAM for readers of staging data.

hack/common.sh, templates/terraform/monster-infrastructure/variables.tf
Found while moving around the dev state.
=> DSPDC-732 Fixup modularization of dev and prod.

templates/helm/orchestration-workflows/templates/clinvar.yaml
update clinvar.yaml template to create a secret and use it, add Repo parameters as well; point to PR branch, point back to master once the corresponding PR is merged
=> Deploy-side update to ingest xml blob in clinvar workflow

templates/helm/orchestration-workflows/templates/clinvar.yaml
The clinvar dataset ID in dev changed, need to update it!
=> update datasetId because it changed

hack/apply-command-center-resources, templates/helm/orchestration-workflows/encode/templates/encode.yaml
Depends on DataBiosphere/encode-ingest#51
=> DSPDC-238 Add new parameters for ENCODE smoke test.

templates/helm/orchestration-workflows/encode/templates/encode.yaml
Adding values that will be used by the changes made [here](https://github.com/DataBiosphere/encode-ingest/pull/53).
=> Add values needed for diffing tabular data in encode

environments/hca-dev/terraform/buckets.tf
=> fix permissions for hca dev env

templates/helm/orchestration-workflows/encode/templates/encode.yaml
To support changes in this PR:
https://github.com/DataBiosphere/encode-ingest/pull/57
=> DSPDC-1055 - Adding repo details to encode template to support orchestration-workflow extensions (soft-delete + ingest steps)

environments/hca/terraform/ebi-bucket.tf
EBI wants to use the STS for S3->GCS transfers.
=> DSPDC-1104 Add STS permissions to EBI bucket.

environments/hca/terraform/k8s.tf, templates/helm/argo-controller/templates/argo.yaml, templates/helm/command-center/templates/argo.yaml, templates/helm/orchestration-workflows/clinvar/templates/workflow.yaml, templates/helm/orchestration-workflows/hca-mvp/templates/workflow.yaml
With some other stuff sneaking in...
=> DSPDC-1069 Rearragne clinvar values

hack/apply-base-cluster-resources, hack/apply-command-center-resources
Not sure if it was the version-bumping that fixed things or my "turn it off and on again" redeploy, but dev is working again.
=> DSPDC-1127 Fix up deployment.

environments/dev/helm/orchestration-workflows/clinvar/values.yaml, environments/dev/helm/orchestration-workflows/encode/values.yaml, environments/prod/helm/orchestration-workflows/clinvar/values.yaml, environments/prod/helm/orchestration-workflows/encode/values.yaml, hack/register-service-account, templates/helm/orchestration-workflows/clinvar/templates/workflow.yaml, templates/helm/orchestration-workflows/clinvar/values.schema.json, templates/helm/orchestration-workflows/encode/templates/encode.yaml, templates/helm/orchestration-workflows/encode/values.schema.json
The Argo server is running [here](https://argo.monster-prod.broadinstitute.org). You can see the ENCODE and ClinVar resources there. I'm running a test ingest for ENCODE to check the plumbing.
=> DSPDC-904 Parameterize scripts for dev vs prod, and add prod settings

environments/prod/helm/orchestration-workflows/encode/values.yaml
Enabling Encode to run weekly in production ([Jira Ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1065)). 
I'll apply these changes once I get approvals.
=> Update encode production values

environments/hca-prod/terraform/buckets.tf, environments/hca-prod/terraform/services.tf, environments/hca/terraform/ebi-bucket.tf, environments/hca/terraform/services.tf
enable STS API in HCA dev and prod, update permissions for SAs and buckets so that it works properly
=> ra-DSPDC-1259-sts-permissions

templates/helm/orchestration-workflows/clinvar/templates/workflow.yaml
corresponding update for the clinvar diff publishing
=> ra-DSPDC-1152-publish-diffs

environments/hca/terraform/ebi-bucket.tf
add enrique and rolando as admins on their staging bucket in dev
=> quick ebi permission update

environments/prod/helm/orchestration-workflows/clinvar/values.yaml, templates/helm/orchestration-workflows/clinvar/templates/workflow.yaml
update version for clinvar workflow.yaml
=> update release version to deploy

environments/hca/terraform/testing.tf
Add test bucket/service account for HCA
=> add test bucket and SA

environments/hca/terraform/buckets.tf
Add IAM for test service account to access temp bucket
=> ra DSPDC 1304 dataflow test

templates/helm/orchestration-workflows/hca-mvp/templates/workflow.yaml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1232)
It looks like there's one more spot that needs to know about the slack notifier.
* Add the slack notifier to the hca mvp helm chart
=> Add notification data

environments/prod/helm/orchestration-workflows/clinvar/values.yaml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1506)
Clinvar ingest is failing, we need to deploy a new version with a fix.
* Pulls in the new version
=> Bump clinvar version

environments/prod/helm/orchestration-workflows/clinvar/values.yaml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1634)
Bumps clinvar to 1.3.1
=> Bump clinvar version to 1.3.1

README.md
The Jade SA setup process has changed, our readme should reflect that.
=> Update readme with recent changes to Jade around SA perms

environments/hca-prod/terraform/buckets.tf, environments/hca/terraform/ebi-bucket.tf
Got the wrong email.
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1635)
Uses the right email.
=> add correct ebi email for bucket permissions

environments/prod/helm/orchestration-workflows/clinvar/values.yaml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1659)
We need to revert a change that went out.
* Bumps the version to the tagged release that contains the revert
=> Bump version for revert

environments/prod/helm/orchestration-workflows/encode/values.yaml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1625)
We have migrated encode to a new dataset + env in prod.
* Updates our configuration to reflect the new settings
=> Update encode prod settings

environments/dev/helm/orchestration-workflows/clinvar/values.yaml, templates/helm/orchestration-workflows/clinvar/templates/workflow.yaml
Sister PR to https://github.com/DataBiosphere/clinvar-ingest/pull/87
Need to update dev clinvar deployment
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1626)
Updates clinvar chart version and adds an `env` argument to the workflow yaml file
=> ra dspdc 1626 clinvar snapshot bug

environments/hca-prod/terraform/lattice_bucket.tf, environments/hca-prod/terraform/services.tf, environments/hca/terraform/lattice-bucket.tf, environments/hca/terraform/services.tf, environments/hca/terraform/variables.tf, templates/terraform/staging-storage/main.tf, templates/terraform/staging-storage/provider.tf, templates/terraform/staging-storage/variables.tf
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1749)
We need to provision a prod staging area for lattice.
* Adds TF configuration for the staging area in HCA prod.
=> [DSPDC-1749] Add lattice prod storage configuration

environments/dev/helm/orchestration-workflows/clinvar/values.yaml, environments/prod/helm/orchestration-workflows/clinvar/values.yaml
We need to update the version references here and deploy them to get the new slack message updates into prod.
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1715)
Updates the version references.
=> update clinvar version

environments/dev/helm/orchestration-workflows/clinvar/values.yaml, environments/prod/helm/orchestration-workflows/clinvar/values.yaml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1861)
* Bumps clinvar to 1.4.2
=> Bump clinvar to 1.4.2

environments/dap/base/infrastructure.tf, environments/dev/terraform/dagster.tf, environments/prod/terraform/dagster.tf, templates/helmfile/environment/prod.yaml, templates/helmfile/monster_comand_center_dagster.lock
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1891)
We need temporary storage for dagster solid results so we can use a multiprocess executor.
* Provisions the buckets in the dev and prod envs
=> Add dagster temp storage buckets

environments/prod/helm/orchestration-workflows/clinvar/values.yaml
The slack token secret path was incorrect.
* Fixes the path
=> Update secret path

environments/hca-prod/terraform/buckets.tf, environments/hca-prod/terraform/dagster.tf, environments/hca-prod/terraform/dns.tf, environments/hca-prod/terraform/variables.tf, environments/hca/terraform/buckets.tf, environments/hca/terraform/dagster.tf, environments/hca/terraform/dns.tf, environments/prod/helm/orchestration-workflows/clinvar/values.yaml, hack/apply-command-center-resources, templates/helm/command-center/values.schema.json, templates/terraform/command-center-project/dns.tf
Update terraform files to reflect reality.
=> Housekeeping

templates/helm/orchestration-workflows/encode/Chart.yaml
[Relevant ticket](https://broadinstitute.atlassian.net/browse/<ticket_id>)
=> Update encode argo controller version

environments/dev/helm/orchestration-workflows/encode/values.yaml
We provisioned a new dataset using the current schema.json in dev.
[Relevant ticket](https://broadinstitute.atlassian.net/browse/<ticket_id>)
Updating the dataProject, datasetName, and datasetId to reflect the new dataset.
=> Update dev encode values to point at new dataset

environments/dev/helm/orchestration-workflows/clinvar/values.yaml, environments/prod/helm/orchestration-workflows/clinvar/values.yaml
https://broadworkbench.atlassian.net/browse/DI-134
Pushes the Clinvar version so that we can attempt to re-run the pipeline.
=> DI-134_Update Clinvar Version in values.yaml

environments/dev/helm/orchestration-workflows/clinvar/values.yaml, environments/prod/helm/orchestration-workflows/clinvar/values.yaml
[DI-243](https://broadworkbench.atlassian.net/browse/DI-243)
[DI-243]: https://broadworkbench.atlassian.net/browse/DI-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DI-243 Version Push

.github/workflows/terraformSecurityCheck.yml, .pre-commit-config.yaml, README.md
[FE-46](https://broadworkbench.atlassian.net/browse/FE-46)
This PR adds a security commenter to check Terraform files and comment on the issues.
Added:
[FE-46]: https://broadworkbench.atlassian.net/browse/FE-46?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> added terraform security commenter

.github/workflows/terraformSecurityCheck.yml, .tfsec/config.yml, environments/dev/terraform/aws.tf
[FE-56](https://broadworkbench.atlassian.net/browse/FE-56)
The PR is to resolve the issues identified by the TFSec check
[FE-56]: https://broadworkbench.atlassian.net/browse/FE-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FE-56 - Remediate Tfsec findings
