.gitignore
environments/README.md
environments/dev/terraform/core.tf
environments/init.sh
templates/terraform/core-project/k8s.tf
templates/terraform/core-project/variables.tf

Flux CD is/was a competitor to Argo CD. The projects have announced that they will eventually fuse (scheduled for 1.6 on the Argo side), so eventually we'll end up using features of both. For now we use Flux CD because it already has Helm 3 support.

DSPDC-590 Add Flux CD installation to base infrastructure.

---

environments/dev/terraform/clinvar.tf
templates/terraform/processing-project/buckets.tf
templates/terraform/processing-project/variables.tf

Add the ability to write out what user accounts (email addresses) should have access to the staging bucket of a processing project. Not 100% sure that the role is right but pretty darn sure about it. I'm also assuming we don't need the delay thing that we used for service accounts because these are user accounts, not service accounts; if that assumption is wrong, I can fix it!
Used the `for_each` pattern listed under the "Resource for_each" in this https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each/
I convert the input `list` into a set using `toset` because the `for_each` pattern doesn't like lists.
(Also added the `access_emails` variable to clinvar's use of the processing project and currently the emails are set to an empty list)
**NOTE** That this PR now …

Ra dspdc 690 add processing bucket emails

---

hack/init-environment.sh

The `install_flux` function contained configurations that we need to use elsewhere.
This PR moves those configurations into their own functions.
- configure_kubernetes
- configure_helm

Abstract configurations for Kubernetes and Helm, to avoid future duplication

---

hack/init-environment.sh
templates/terraform/command-center-project/cloudsql.tf

Created a new function in `init-environment.sh` to set up CloudSQL Proxy. The function:
1. Configures helm
2. Reads config values from vault and writes them to GKE 
3. Installs or upgrades CloudSQL Proxy with the necessary secrets and other configs
Also, these changes update terraform to write the CloudSQL region and project name to vault.

Sw dspdc 670 Set up CloudSQL Proxy in dev environment

---

environments/dev/terraform/gcs.tf
hack/init-environment.sh
templates/terraform/command-center-project/cloudsql.tf
templates/terraform/google-sa/README.md
templates/terraform/google-sa/main.tf
templates/terraform/google-sa/outputs.tf
templates/terraform/google-sa/provider.tf
templates/terraform/google-sa/variables.tf

Add google service account module and use it in the command-center and environments/terraform/gcs; applied it, didn't get any errors, did a bunch of `terraform mv` commands to try to not break things. I'm mostly concerned about my updates to the init bash script, so please take a close look at those changes!

Ra dspdc 696 google sa module

---

environments/dev/terraform/clinvar.tf
environments/dev/terraform/command-center.tf
hack/README.md
hack/init-cluster-resources
hack/init-environment.sh
templates/terraform/command-center-project/k8s.tf
templates/terraform/command-center-project/variables.tf
templates/terraform/k8s-master/main.tf
templates/terraform/k8s-master/outputs.tf
templates/terraform/k8s-master/variables.tf
templates/terraform/processing-project/k8s-master.tf
templates/terraform/processing-project/variables.tf

Instead of writing kubeconfigs to local disk, we write them to Vault. The hack scripts then need to read the configs from Vault to deploy things. Since my other two in-flight tickets involve re-writing / splitting most of `init-environment.sh`, I stuck the demo of "reading configs from Vault" in a new script which should be pretty stable.
Putting this out there as a draft because I haven't tried running it yet. Will wait for the dust to settle on the other in-flight TF tickets.

DSPDC-704 DSPDC-729 Write kubeconfigs to Vault and read them in scripts.

---

templates/terraform/processing-project/service-accounts.tf

Creating a service account to run GKE system pods for processing projects.
Note: These changes are pretty similar to those in [a previous PR ](https://github.com/broadinstitute/monster-deploy/pull/20/files) which created a similar service account for the command center.

Add processing project service account to run GKE pods

---

environments/dev/terraform/clinvar.tf
environments/dev/terraform/gcs.tf
templates/terraform/command-center-project/service-accounts.tf
templates/terraform/processing-project/buckets.tf
templates/terraform/processing-project/provider.tf
templates/terraform/processing-project/service-accounts.tf

Add a service account to run dataflow jobs to the processing project module; add bucket permissions for the service account on the temp and staging buckets.
Add a service account to launch dataflow jobs; add bucket permissions for the service account on the temp bucket.
Add a service account to upload artifacts to GCS; add bucket permissions for the service account on the artifact bucket.

Ra dspdc 699 dataflow runner

---

environments/dev/terraform/command-center.tf
templates/terraform/command-center-project/cloudsql.tf
templates/terraform/command-center-project/variables.tf

A small change to add databases and users to the command-center cloudsql instance ([Jira Ticket](https://broadinstitute.atlassian.net/browse/DSPDC-706)).
Databases:
- argo
- airflow
- datarepo
- stairway
Users:
- argo
- airflow
- datarepo

Add databases and users to command-center cloudsql instance

---

templates/terraform/command-center-project/k8s.tf
templates/terraform/k8s-master/variables.tf
templates/terraform/k8s-node-pool/main.tf
templates/terraform/k8s-node-pool/variables.tf
templates/terraform/processing-project/k8s-master.tf

-Added a required string param "service_account_email" to the /k8s-node-pool and /k8s-master variables.tf files
-Using the new parameter in the /k8s-node-pool main script to set the "service_account" param
-Updated /command-center-project/k8s.tf and /processing-project/k8s-master to pass the SA emails

QH DSPDC-698 - Extending k8s-node-pool to take service account email input

---

environments/dev/terraform/clinvar.tf
templates/terraform/processing-project/buckets.tf
templates/terraform/processing-project/variables.tf

Adding an email (for the account running the Dev Test Repo) to the list of bucket readers for the clinvar dev environment.

Add email to list of bucket readers for Clinvar dev

---

environments/v2f-prod/terraform/bucket.tf
hack/apply-cluster-resources
hack/apply-helm-releases
templates/terraform/command-center-project/service-accounts.tf

I think this is p straightforward! I have hard coded the bucket to write to, I put it in the command-center's service accounts file because we're not spinning up a processing project for this, and I believe the objectCreator role is correct; those are the things I'd love to get double checked if anyone sees anything awry with 'em.

add v2f service account and attach IAM for bucket

---

templates/terraform/processing-project/bigquery.tf
templates/terraform/processing-project/services.tf

Adding BigQuery to the processing project [(Jira Ticket) ](https://broadinstitute.atlassian.net/browse/DSPDC-815):
- Added to the list of APIs enabled
- Created a BigQuery dataset and assigned roles to the command center service account
The terraform output looks like:
```
+ resource "google_bigquery_dataset" "dataset" {
+ creation_time               = (known after apply)
+ dataset_id                  = "bigquery-dataset-dev"
+ default_table_expiration_ms = 604800000
+ delete_contents_on_destroy  = false
+ description                 = "BigQuery development dataset"
+ etag                        = (known after apply)
+ friendly_name               = "BigQuery Dev Dataset"
+ id                          = (known after apply)
+ last_modified_time          = (known after apply)
+ location …
```

Sw dspdc 815 add bigquery to processing project

---

templates/terraform/processing-project/bigquery.tf
templates/terraform/processing-project/service-accounts.tf

After #42 was merged, I tried to apply the terraform changes and got the following error because the role `bigquery.jobUser` was being applied at the wrong level:
```
Error: Error creating Dataset: googleapi: 
Error 400: IAM setPolicy failed for Dataset broad-dsp-monster-clingen-dev:monster_staging_data: Role roles/bigquery.jobUser is not supported for this resource.
```
This PR is to fix that issue by applying the role at the project level instead of the dataset level.

Bug fix: Roles for bigquery dataset

---

templates/helm/command-center/templates/clinvar.yaml

The hard-coded values are the same as I used for testing in DataBiosphere/clinvar-ingest#14

DSPDC-801 Add ClinVar chart to command-center releases.

---

environments/v2f-prod/terraform/bucket.tf

[Jira Ticket](https://broadinstitute.atlassian.net/browse/DSPDC-886) 
Adding schaluva@broadinstitute.org as an admin to the v2f bucket.
Terraform output:
```
+ resource "google_storage_bucket_iam_member" "v2f_admin_iam" {
+ bucket = "variant-to-function-result-sets"
+ etag   = (known after apply)
+ id     = (known after apply)
+ member = "user:schaluva@broadinstitute.org"
+ role   = "roles/storage.objectAdmin"
}
Plan: 1 to add, 0 to change, 0 to destroy.
```

Add user as admin to v2f bucket

---

environments/dev/terraform/clinvar.tf
templates/terraform/processing-project/bigquery.tf

We'd managed to accumulate a few hundred-thousand files in the bucket from recent testing.
I also tweaked our BQ access controls here. When I was viewing the `plan` output for the bucket it showed that:
1. The BQ API rewrites non-primitive roles (i.e. `roles/bigquery.dataEditor`) to primitive roles (`WRITER`) when it can, so using the non-primitive role will always cause a TF diff.
2. If no explicit owner is marked in the access block, whoever applies the TF is automatically made an owner.

DSPDC-731 Re-enable TTL on clinvar staging storage

---

hack/apply-base-cluster-resources
templates/helm/command-center/templates/argo.yaml
templates/helm/crd-operators/Chart.yaml

Looks like flux moved some stuff around in their repo, but nothing broke on a test deploy.

Bump FluxCD and Argo versions.

---

hack/apply-orchestration-workflows
templates/helm/orchestration-workflows/templates/encode.yaml
templates/helm/orchestration-workflows/values.schema.json

Fixing a couple of typos, to allow the encode orchestration workflow from https://github.com/broadinstitute/monster-deploy/pull/60 to execute.
I already ran this on dev with the new changes to make sure it works this time.

Fix typos in encode orchestration workflow

---

templates/terraform/processing-project/buckets.tf

^what the title says. This is for long term storage of argo logs. Here is the plan:
```
Terraform will perform the following actions:
+ resource "google_storage_bucket" "argo_logs_storage" {
+ bucket_policy_only = (known after apply)
+ force_destroy      = false
+ id                 = (known after apply)
+ location           = "US"
+ name               = "broad-dsp-monster-clingen-dev-argo-logs-storage"
+ project            = (known after apply)
+ self_link          = (known after apply)
+ storage_class      = "STANDARD"
+ url                = (known after apply)
}
+ resource "google_storage_bucket_iam_member" "command_center_argo_logs_bucket_iam" {
+ bucket = "broad-dsp-monster-clingen-dev-argo-logs-storage"
+ etag   = (known after apply)
+ id     = (known after apply)
+ member = …
```

add a bucket and iam role to the processing project module

---

templates/terraform/monster-infrastructure/clinvar.tf
templates/terraform/monster-infrastructure/encode.tf
templates/terraform/processing-project/buckets.tf
templates/terraform/processing-project/variables.tf

Plan output is:
```
+ resource "google_storage_bucket" "results_storage" {
+ bucket_policy_only = (known after apply)
+ force_destroy      = false
+ id                 = (known after apply)
+ location           = "US"
+ name               = "broad-dsp-monster-clingen-dev-ingest-results"
+ project            = (known after apply)
+ self_link          = (known after apply)
+ storage_class      = "STANDARD"
+ url                = (known after apply)
}
+ resource "google_storage_bucket_iam_member" "results_external_readers" {
+ bucket = "broad-dsp-monster-clingen-dev-ingest-results"
+ etag   = (known after apply)
+ id     = (known after apply)
+ member = "group:clingendevs@broadinstitute.org"
+ role   = "roles/storage.objectViewer"
}
+ resource "google_storage_bucket_iam_member" …
```

DSPDC-979 Add optional results bucket to processing-project module.

---

environments/dev/terraform/aws.tf
environments/dev/terraform/main.tf
environments/prod/terraform/main.tf
hack/apply-command-center-resources
hack/common.sh
templates/terraform/aws-sa/README.md
templates/terraform/aws-sa/main.tf
templates/terraform/aws-sa/outputs.tf
templates/terraform/aws-sa/provider.tf
templates/terraform/aws-sa/variables.tf
templates/terraform/monster-infrastructure/encode.tf
templates/terraform/monster-infrastructure/provider.tf

Plan output is:
```
Terraform will perform the following actions:
- resource "aws_iam_access_key" "s3_transfer_user_key" {
- id                = "AKIA53RL2ZNQGEJAS2GD" -> null
- secret            = (sensitive value)
- ses_smtp_password = (sensitive value)
- status            = "Active" -> null
- user              = "monster-s3-tester" -> null
}
- resource "aws_iam_user" "s3_transfer_user" {
- arn           = "arn:aws:iam::952500931424:user/monster-s3-tester" -> null
- force_destroy = false -> null
- id            = "monster-s3-tester" -> null
- name          = "monster-s3-tester" -> null
- path          = "/" -> null
- tags          = {} -> null
- unique_id     = "AIDA53RL2ZNQGN3WIIHSL" -> null
}
- resource "vault_generic_secret" "s3_transfer_user_secret" {
- data         = (sensitive …
```

DSPDC-915 Generate AWS users for ENCODE.

---

templates/helm/command-center/templates/argo.yaml
templates/helm/orchestration-workflows/clinvar/templates/workflow.yaml
templates/terraform/command-center-project/k8s.tf

* Pin newest Argo chart versions
* Set a parallelism of 1 to avoid failures on Jade side
* Bump disk size to avoid failures because of DiskPressure

Fixups for ClinVar

---

environments/dev/helm/orchestration-workflows/clinvar/values.yaml
environments/dev/helm/orchestration-workflows/encode/values.yaml
templates/helm/argo-controller/Chart.yaml
templates/helm/argo-controller/templates/argo.yaml
templates/helm/argo-controller/values.schema.json
templates/helm/command-center/values.schema.json
templates/helm/orchestration-workflows/clinvar/Chart.yaml
templates/helm/orchestration-workflows/clinvar/templates/workflow.yaml
templates/helm/orchestration-workflows/encode/Chart.yaml

Our latest update to the argo-controller chart introduced a required input for "log bucket". The values of those buckets vary across projects and environments, so it's not easy to encode a uniform pattern in the generic "command center" deployment.
I've been questioning the value of having central "command center" infrastructure vs. stand-alone deployments for each project. To take a step in the stand-alone direction, I refactored the argo-controller deployment to run as part of our workflow deploy in each namespace. The log-bucket name is passed in the `values.yaml` used for the specific project/environment.

Refactor how we deploy argo controllers.

---

environments/hca-prod/terraform/buckets.tf

Fixed workload identity; we have historically been using the project name throughout our TF code, but for hca-prod, we were not able to secure a name that is the exact same as the project id, which caused some weirdness. Turns out using the project id prepends "projects/" to the id, which resulted in the service account name being invalid, which makes sense. Providing the project ID as a local variable and passing that in fixed it.

Ra dspdc 1252 workload identity issue

---

.github/PULL_REQUEST_TEMPLATE.md
environments/hca-prod/terraform/k8s.tf
environments/hca/terraform/k8s.tf
templates/helm/argo-controller/Chart.yaml
templates/helm/argo-controller/templates/argo.yaml
templates/helm/orchestration-workflows/hca-mvp/Chart.yaml
templates/helm/orchestration-workflows/hca/Chart.yaml
templates/helm/orchestration-workflows/hca/templates/workflow.yaml

When running a large import, the k8s cluster/argo workflow process was struggling at times. Namely, the argo-controller kept crashing. We ought to point to a new version of our argo-controller chart that makes sure the controller has more memory, and allocate slightly beefier machines for the cluster.
- bump up machine types for hca dev and prod
- update argo controller version and corresponding chart version
- fix use of projectId vs projectName in hca orch-workflow

Update HCA infrastructure/deployment to be more performant

---

environments/hca-prod/helm/orchestration-workflows/hca/values.yaml
environments/hca/helm/orchestration-workflows/hca-mvp/values.yaml

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1232) 
We want slack notifications when `hca-ingest` failures.
To get that running, we need to grab the slack oauth token and put it in K8s so Argo can get at it.
* This is somewhat hand-wavy: my understanding is that these values.yaml files are what's responsible for building up the secrets in k8s, if anyone can confirm/deny please pipe up.
* I've put the needed oauth token in vault already
* To roll this out, I _think_ I'll need to run `hack/apply-orchestration-workflow`, again please comment if I'm on the wrong track with that.

[DSPDC-1232] Slack notification secrets

---

templates/helm/orchestration-workflows/hca-mvp/templates/workflow.yaml
templates/helm/orchestration-workflows/hca/templates/workflow.yaml

These secrets need to be in place for HCA in prod and dev (I had them set locally but failed to get them into git)
* Updates the workflow yamls for hca-mvp and hca prod to reflect the slack oauth token secrets

Add slack secrets to HCA prod and dev workflow yamls

---

environments/prod/helm/orchestration-workflows/encode/values.yaml
templates/helm/orchestration-workflows/encode/Chart.yaml
templates/helm/orchestration-workflows/encode/templates/encode.yaml

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1405)
We should fire slack alerts when encode's prod ingest fails.
* "True's up" with a slack secret structure that we're leveraging for hca + clinvar
* Updates the argo controller chart version to pull in [these changes](https://github.com/broadinstitute/monster-helm/commit/37b67404061f2f008af13bc8f3e06dae7180976b)
* Updates the encode prod ingest to run on Sunday mornings

Encode slack configuration

---

environments/dev/helm/orchestration-workflows/clinvar/values.yaml
templates/helm/orchestration-workflows/hca-mvp/templates/workflow.yaml

Jade updated their dev deployment so now everything works off of a single profile ID. If I understand the changes correctly, all we need to do is use that default profile ID now.
Updates the old profileId to the new default profileId.

update profileId to the new default value everywhere applicable

---

environments/prod/helm/orchestration-workflows/encode/values.yaml
templates/helm/orchestration-workflows/encode/templates/encode.yaml

We deploy specific tags to prod for `encode-ingest`. This means we have not shipped encode since v1.0.0-M2 was cut in June 2020. Additionally, our use of the `broadinstitute/setup-chart-releaser` is broken due to breaking changes GH made
with using `add-path`, which will be tough to fix since that GH action comes from an [archived repo](https://github.com/broadinstitute/setup-chart-releaser). 
I propose we ship `master` to prod for encode going forward.
* Points at the `master` github ref, rather than relying on a tag.
* Adds back the `smokeTest` hash in the encode orchestration YAML, as this is needed to successfully render the slack template.

Ship master when deploying encode-ingest to prod

---

templates/helm/orchestration-workflows/clinvar/Chart.yaml

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1344)
We need to upgrade for Clinvar to the argo-controller 0.0.1 as 0.0.0 is no longer present in the repo.
* Points the clinvar helm chart at version 0.0.1 of the argo-controller template.

Upgrade to the latest argo controller chart

---

environments/hca/terraform/pubsub.tf

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1465)
The sub name provided in the previous PR was formatted incorrectly (discovered after running TF)
* Updates the sub name to reflect reality

Update subscription name when granting permissions

---

environments/hca-prod/terraform/services.tf

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1465)
Prior to setting up topics and subscriptions, we need to enable the pubsub API (the terraform plan will fail if this is not setup first)
* Turns on the API for `hca-prod`

[DSPDC-1465] Enable the pubsub API in hca-prod

---

environments/hca-prod/terraform/pubsub.tf

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1465)
The sub name in the pubsub config for HCA prod was incorrect.
* Fixes the sub name to reflect reality

Fix subscription name

---

templates/helm/argo-controller/templates/argo.yaml
templates/helm/command-center/templates/argo.yaml

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1564)
We need more memory to increase the # of in-flight ingests we can support for HCA.
* Pulls in an updated chart that bumps the memory allocation for the argo controller

Bump argo controller chart version

---

environments/hca/terraform/dns.tf

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1590)
We need a global static IP and DNS name for argo CD in HCA dev.
* Adds an `hca-argocd` DNS name to the terraform `dns_names` module

[DSPDC-1590] Configure a DNS name and global static IP for argocd in hca-dev

---

environments/prod/helm/orchestration-workflows/clinvar/values.yaml

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1627)
ClinVar can't accomodate a resubmit of a job due to the bug described in this [DSPDC-1626](https://broadinstitute.atlassian.net/browse/DSPDC-1626)
* This PR bumps the version to a new tag to force a full reingest of the failed release.

[DSPDC-1627] Bump clinvar release to force a resubmit of a failed job

---

environments/hca-prod/terraform/buckets.tf
environments/hca-prod/terraform/dagster.tf
environments/hca/terraform/buckets.tf
environments/hca/terraform/dagster.tf
templates/terraform/google-sa/outputs.tf

This configures the Dagster service account to be able to interact with the services we need, and sets up the Google side of binding it to the Kubernetes cluster running Dagster (so pods can interact with Google services as this SA). It also adds the requisite permissions for the SA to authenticate with Argo Workflows' REST API.

Configure IAM role for Dagster to interact with Google services, Argo

---

environments/hca-prod/terraform/dagster.tf
environments/hca/terraform/dagster.tf

Terraform apply is failing with "required field 'project' not specified" because we neglected to link the provider to the resources in this file.

Specify provider for dagster IAM resources to link to correct project

---

environments/hca-prod/terraform/buckets.tf
environments/hca/terraform/ebi-bucket.tf
environments/prod/helm/orchestration-workflows/clinvar/values.yaml

We should manage external permissions with externally managed email groups, and use these groups in our code instead of hard coding individuals.
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1635)
Changes EBI and UCSC staging bucket ownership to email groups instead of particular individuals.

Ra dspdc 1635 bucket groups

---

environments/hca-prod/terraform/buckets.tf
environments/hca-prod/terraform/dagster.tf
environments/hca/terraform/buckets.tf
environments/hca/terraform/dagster.tf

Currently, the Dagster runner can't access the staging buckets we use for HCA imports, which prevents it from running the stage-data pipeline.
This also removes some duplicate IAM binding resources and standardizes some formatting.

Grant Dagster runner SA access to our staging buckets

---

environments/hca-prod/terraform/dagster.tf
environments/hca/terraform/dagster.tf
hack/apply-terraform

Temp bucket access is required to run Dataflow jobs that access the temp bucket using Dagster.

Give Dagster SA access to temp bucket

---

hack/apply-terraform

In the previous version of this script there was no way to run TF commands like "force-unlock" which accept arguments. This now passes all arguments after the first as arguments to `terraform`, letting you do things like `./apply-terraform dev force-unlock 1234567890`

Allow passing args to alternative terraform commands

---

environments/dev/helm/orchestration-workflows/clinvar/values.yaml

We are unable to test certain things in dev due to certain parts of the clinvar workflow only running when the version is pinned (as opposed to using "latest").
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1656)
Changes chart values to versioned ref instead of git master branch for clinvar dev, aka pins the version for dev

ra dspdc 1656 clinvar dev auto snapshot

---

environments/hca/terraform/testing.tf

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1698)
Our E2E dagster pipeline tests need to create a "staging" dataset in our HCA dev BQ project
* Grants the `hca-test-runner` SA the required BQ permissions to create a dataset

[DSPDC-1698] Give HCA dev test runner SA appropriate BQ permissions

---

.github/workflows/terraformApply.yml

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1689)
Keeps parity with behavior of the manual script
* Adds a Github action to our terraformApply action that sends a Slack notification to monster-deploy
* Initially the notification indicates that the deploy is in progress, and it is then updated with the pass/fail status of the deployment.
* Notification includes a link to the commit being deployed as well as the workflow running the deploy (which will be linked to the triggering user)

Fire Slack notifications to monster-deploy on merges to master

---

.github/workflows/terraformApply.yml

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1710)
We are not applying terraform changes on merge to master for DAP.
* Adds the relevant DAP envs to the matrix

Include DAP when applying on merge

---

environments/hca-prod/terraform/buckets.tf
environments/hca-prod/terraform/cloudsql.tf
environments/hca-prod/terraform/dagster.tf
environments/hca-prod/terraform/dns.tf
environments/hca-prod/terraform/k8s.tf
environments/hca-prod/terraform/networks.tf
environments/hca-prod/terraform/provider.tf
environments/hca-prod/terraform/pubsub.tf
environments/hca-prod/terraform/services.tf
environments/hca/terraform/buckets.tf
environments/hca/terraform/dagster.tf
environments/hca/terraform/ebi-bucket.tf
environments/hca/terraform/k8s.tf
environments/hca/terraform/networks.tf
environments/hca/terraform/pubsub.tf
environments/hca/terraform/services.tf
environments/hca/terraform/sinks.tf
environments/hca/terraform/testing.tf
environments/v2f-prod/terraform/bucket.tf

Want to swap out our Terraform config to utilize google instead of google-beta provider
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1663)
Swaps google-beta -> google provider and was tested locally by performing terraform plan after each change in a file

Ep dspdc 1663 google beta provider

---

environments/hca-prod/terraform/buckets.tf
environments/hca-prod/terraform/dagster.tf
environments/hca-prod/terraform/pubsub.tf
environments/hca/terraform/dagster.tf
environments/hca/terraform/pubsub.tf

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1727)
There is a race when creating the ebi staging writer pubub IAM permissions; we need to wait for subscription to be created before granting the permissions.
* Adds a depends_on to the IAM user permission operations
* Fixes dagster dataflow user bindings so they don't get clobbered after every terraform apply

Fix pubsub IAM race 

---

.github/CODEOWNERS

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1735)
There are sensitive parts of our terraform infrastructure that require approval by the Monster tech lead.
* Adds a `CODEOWNERS` file that sets `aherbst-broad` as the owner for any `.tf` changes, and requires a review.

[DSPDC-1735] Add codeowners file for terraform

---

.github/workflows/terraformPlan.yml

The comments for our Terraform plans don't provide any information not available from the Github job logs, and they massively clutter our PRs.0
* Disables comments generated by TF plan jobs
* Reduces the log level of our terraform plan jobs to INFO so the only thing displayed (by default) is the plan output.
Plans will still run and pass/fail, and we can review the results of those plans by looking at the logs of the plan step in the Github actions.

Turn off TF plan comments, reduce debug level to INFO

---

environments/hca-prod/terraform/dagster.tf
environments/hca/terraform/dagster.tf

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1751)
* Creates a bucket in HCA dev and prod to store Dagster run data, and gives the Dagster runner SA permission to access the bucket.
We may want to, in the future, set up a lifecycle rule to clean up intermediate outputs after a few days-to-weeks, but intermediate outputs will (for now) be extremely small, so this is not urgent to do.

Create buckets to store HCA dagster run records and intermediate job outputs

---

.github/workflows/terraformPlan.yml
templates/terraform/staging-storage/main.tf

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1749)
We need to use the project ID, not the project name when setting up the pubsub IAM user.
* Swaps project ID for name where appropriate
* Removes the INFO level logging on the `terraform plan` check as I find it a major pain to scroll for minutes to get the actual plan.

Use project ID when setting up IAM user for pubsub, not name

---

templates/terraform/staging-storage/main.tf

The latest TF apply failed; I believe this may be due to a race between creating the IAM user and the pubsub topic to which they are being granted perms.
* Adds a `depends_on` in the IAM user creation on the pubsub topic creation

Add dependency on pubsub topic when creating IAM writer

---

templates/helm/argo-controller/templates/argo.yaml

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1838)
We need to pull in this fix to avoid workflows hanging when Argo attempts to PATCH gigantic YAML files in the K8S API.
* Pulls in the fix, which will use a database rather than K8S as it's persistent store for workflow state.

Bump controller chart version to pull in workflow YAML updating fix

---

environments/prod/helm/orchestration-workflows/clinvar/values.yaml
templates/helm/argo-controller/templates/argo.yaml

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1858)
The previous fix that set the argo controller to store workflow status in the DB got clobbered because the changes were never committed to source control.
* Bumps the argo controller and clinvar versions to reflect reality

Bump clinvar version and argo version

---

environments/dev/helm/orchestration-workflows/clinvar/values.yaml
environments/prod/helm/orchestration-workflows/clinvar/values.yaml

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1864)
We need to be resilient to BQ 502s.
* Pulls in the latest clinvar version with BQ 502 fixes.

Bump clinvar version

---

environments/hca-prod/terraform/buckets.tf

Dev GCP service account for exporter has access to the prod bucket and need to remove that permission
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1863)
removes 
"client_email": "ebi-staging-writer@broad-dsp-monster-hca-dev.iam.gserviceaccount.com"
from hca-prod

Remove ebi dev stage writer from prod

---

environments/dev/terraform/dagster.tf
environments/dev/terraform/variables.tf
environments/prod/terraform/dagster.tf
environments/prod/terraform/main.tf
environments/prod/terraform/variables.tf

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1891)
We need IAM users for the monster "command center" dagster K8S service accounts so we can grant them the appropriate
permissions in the DAP GCP project.
* Adds the role binding terraform

Add K8S monster dagster role bindings

---

environments/hca-prod/terraform/dagster.tf
environments/hca/terraform/dagster.tf

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1898)
We need a place to store manifest files for DCP releases.
* Provisions the buckets in dev + prod

Setup dcp releases bucket to hold manifest files

---

environments/dap/base/infrastructure.tf

The dagster runner needs permissions to write to the DAP storage bucket.
* Sets the correct permissions

Set permissions on dap run storage bucket

---

environments/dev/helm/orchestration-workflows/clinvar/values.yaml
environments/prod/helm/orchestration-workflows/clinvar/values.yaml
templates/helm/orchestration-workflows/clinvar/templates/workflow.yaml

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1902)
To support dual writing, we are going to need to create a new "real prod" clinvar deployment. This notifications from this deployment should not ping the regular #clinvar-ingest channel to avoid confusion. 
* Updates the clinvar values.yaml to thread through the channel ID
Note that the channel_id inclusion in the chart is now supported in clinvar 1.4.7, implemented in this pr https://github.com/DataBiosphere/clinvar-ingest/pull/96

Update clinvar deployment info

---

environments/hca-prod/terraform/dagster.tf
environments/hca-prod/terraform/dns.tf
environments/hca/terraform/buckets.tf
environments/hca/terraform/dagster.tf
environments/hca/terraform/dns.tf
environments/prod/helm/orchestration-workflows/clinvar/values.yaml

We need to be able to read from the EBI staging bucket in DEV from our dagster pipelines.
* Adds the needed permission
* Renames the etl partitions bucket to reflect reality

Add dagster runner SA permissions to EBI staging bucket

---

templates/helmfile/environment/dev.yaml
templates/helmfile/environment/prod.yaml

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1954)
We need to capture stderr + stdout from our Dagster runs to ease debugging.
* Sets up a compute log manager and points at the dagster log storage buckets

Setup Dagster log storage

---

templates/helm/orchestration-workflows/clinvar/templates/workflow.yaml

The automated nightly ClinVAR ingest failed the past two nights. Upon investigation, it was found that an IO exception was being thrown in the "extra-xml" step of the pipeline due to there being "No space left on device". Digging in a bit, we found that the downloadSize and extractSize volume parameters in templates/helm/orchestration-workflows/clinvar/templates/workflow.yaml needed to be increased.
[Relevant ticket](https://broadworkbench.atlassian.net/browse/DI-9)
Increases the downloadSize and extractSize volume parameters in templates/helm/orchestration-workflows/clinvar/templates/workflow.yaml to accommodate the growing size of the ClinVAR archives. The increases are from 2Gi to 5Gi and from 15Gi to 40Gi, respectively.

Increases download and extract size

---

environments/dev/helm/orchestration-workflows/clinvar/values.yaml
environments/prod/helm/orchestration-workflows/clinvar/values.yaml

The dual writer flow is no more, and we should be pointing at the latest clinvar version.
* Updates the clinvar version in dev and prod
* Removes unneeded chart values related to the dual writer

Fix clinvar values to remove dual writer references
